{{- $v := .Values.backstage -}}
{{- if $v.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ccf.backstage.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "ccf.backstage.labels" . | nindent 4 }}
    app.kubernetes.io/component: backstage
spec:
  {{- if $v.ingress.className }}
  ingressClassName: {{ $v.ingress.className | quote }}
  {{- end }}
  {{- if $v.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ $v.ingress.host | quote }}
      secretName: {{ $v.ingress.tls.secretName | quote }}
  {{- end }}
  rules:
    - host: {{ $v.ingress.host | quote }}
      http:
        paths:
          - path: {{ $v.ingress.path | quote }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "ccf.backstage.fullname" . }}
                port:
                  number: {{ $v.service.port }}
{{- end }}
