{{- $v := .Values.netbox -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ccf.netbox.authSecretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "ccf.netbox.labels" . | nindent 4 }}
type: Opaque
stringData:
  secret_key: {{ $v.secretKey | quote }}
  db_password: {{ default "" $v.externalDatabase.password | quote }}
  tasks_password: {{ default "" $v.tasksDatabase.password | quote }}
  cache_password: {{ default "" $v.cachingDatabase.password | quote }}
  superuser_password: {{ $v.superuser.password | quote }}
  superuser_api_token: {{ $v.superuser.apiToken | quote }}
  email_password: ""
